name: CI Pipeline for Playwright with pnpm
on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.14.4
      - name: Install dependencies
        run: pnpm install
  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.14.4
      - name: Install dependencies
        run: pnpm install
      - name: Run Playwright tests
        run: pnpm test
